function [png] = draw_pile_pdf() 
png.PN_name = 'Draw Pile';

png.set_of_Ps = {'pDP_Draw_Pile','pDP_Move','pDP_Dealer'};
png.set_of_Ts = {'tDPi_Dealer','tDPe_Out','tDPe_Turn','tDPe_Move'}; 
png.set_of_As = {
    'tDPi_Dealer','pDP_Draw_Pile',1, ...
    'pDP_Draw_Pile','tDPe_Out',1, ...
    'pDP_Dealer', 'tDPi_Dealer', 1, ...
    'pDP_Draw_Pile', 'tDPe_Turn', 1, ...
    'tDPe_Turn', 'pDP_Draw_Pile', 1, ...
    'pDP_Move', 'tDPe_Out', 1, ...
    'tDPe_Move', 'pDP_Move', 1, ...
    };
