function [png] = draw_pile_pdf() 
png.PN_name = 'Draw Pile';

png.set_of_Ps = {'pDP_Draw_FaceUp_Pile','pDP_Draw_FaceDown_Pile', ...
    'pDP_Move_Out','pDP_Dealer', 'pDP_Turn', 'pDP_Move_Init'};
png.set_of_Ts = {'tDPi_Dealer','tDPe_Out','tDPe_Turn','tDPi_Turn', ...
    'tDPe_Move', 'tDPi_Enable_FP_Trans', 'tDPi_Flip_Pile', 'tDPi_Move_Init'}; 
png.set_of_As = {
    'tDPi_Dealer','pDP_Draw_FaceDown_Pile',1, ...
    'pDP_Draw_FaceUp_Pile','tDPe_Out',1, ...
    'pDP_Dealer', 'tDPi_Dealer', 1, ...
    'pDP_Draw_FaceDown_Pile', 'tDPi_Turn', 1, ...
    'tDPi_Turn', 'pDP_Draw_FaceUp_Pile', 1, ...
    'pDP_Move_Out', 'tDPe_Out', 1, ...
    'tDPe_Move', 'pDP_Move_Out', 1, ...
    'pDP_Draw_FaceUp_Pile', 'tDPi_Flip_Pile', 1, ...
    'tDPi_Flip_Pile', 'pDP_Draw_FaceDown_Pile', 1, ...
    'pDP_Turn', 'tDPi_Enable_FP_Trans', 1, ...
    'pDP_Turn', 'tDPi_Turn', 1, ...
    'tDPe_Turn', 'pDP_Turn', 1, ...
    'pDP_Move_Init', 'tDPi_Move_Init', 1, ...
    'tDPi_Move_Init', 'pDP_Move_Out', 1, ...
    };
png.set_of_Is = {
    'pDP_Dealer', 'tDPe_Move', 1, ...
    'pDP_Dealer', 'tDPe_Turn', 1, ...
    'pDP_Dealer', 'tDPi_Enable_FP_Trans', 1, ...
    'pDP_Dealer', 'tDPi_Turn', 1, ...
    'pDP_Turn', 'tDPi_Move_Init', 1, ...
    'pDP_Draw_FaceDown_Pile', 'tDPi_Enable_FP_Trans', 1
    };