function [png] = foundation_stack_spades_pdf() 
png.PN_name = 'Foundation stack - spades';

png.set_of_Ps = {'pGSi_GameStack','pGSi_Move','pGSi_Dealer'};
png.set_of_Ts = {'tGSi_Dealer','tGSe_Out','tGSe_Turn','tGSe_Move'}; 
png.set_of_As = {
    'tGSi_Dealer','pGSi_GameStack',1, ...
    'pGSi_GameStack','tGSe_Out',1, ...
    'pGSi_Dealer', 'tGSi_Dealer', 1, ...
    'pGSi_GameStack', 'pGSe_Turn', 1, ...
    'pGSe_Turn', 'pGSi_GameStack', 1, ...
    'pGSi_Move', 'tGSe_Out', 1, ...
    'tGSe_Move', 'pGSi_Move', 1, ...
    };
