function [png] = foundation_stack_spades_pdf() 
modname = 'spades';
png.PN_name = strcat('Foundation stack - ',modname);


png.set_of_Ps = {strcat('pFS_',modname,'_Stack'),strcat('pFS_',modname,'_Move')};
png.set_of_Ts = {strcat('tFSe_',modname,'_Add'),strcat('tFSe_',modname,'_Move'),strcat('tFSe_',modname,'_Out')}; 
png.set_of_As = {
    strcat('tFSe_',modname,'_Add'),strcat('pFS_',modname,'_Stack'),1, ...
    strcat('pFS_',modname,'_Stack'),strcat('tFSe_',modname,'_Out'),1, ...
    strcat('tFSe_',modname,'_Move'), strcat('pFS_',modname,'_Move'), 1, ...
    strcat('pFS_',modname,'_Move'), strcat('tFSe_',modname,'_Out'), 1, ...
    };
