function [png] = game_stack_pdf() 
png.PN_name = 'Game stack';

png.set_of_Ps = {'pGS_GameStack','pGS_Move','pGS_Dealer'};
png.set_of_Ts = {'tGSi_Dealer','tGSe_Out','tGSe_Turn','tGSe_Move'}; 
png.set_of_As = {
    'tGSi_Dealer','pGS_GameStack',1, ...
    'pGS_GameStack','tGSe_Out',1, ...
    'pGS_Dealer', 'tGSi_Dealer', 1, ...
    'pGS_GameStack', 'tGSe_Turn', 1, ...
    'tGSe_Turn', 'pGS_GameStack', 1, ...
    'pGS_Move', 'tGSe_Out', 1, ...
    'tGSe_Move', 'pGS_Move', 1, ...
    };
